### ISSUE TITLE
Discard Non-Voiced Audio

### ISSUE THREAD

**Issue by zesky18** [bpwhelan/TrimJapaneseGameAudio#21]
Give the script the ability to discard audio when it detects that there is no voice in the OBS recording. It's awkward to have multiple Anki cards with audio files that have nothing but background noise. In this case, what the user really want is the screenshot, not the audio.

**Comment by bpwhelan** [comment]
I know there was a specific reason for me having it like this, but im sure it was probably wrong.

Will likely implement in the next day or so.
