### ISSUE TITLE
Add Time Buffer to Config

### ISSUE THREAD

**Issue by zesky18** [bpwhelan/TrimJapaneseGameAudio#22]
Currently, it is possible to change the buffer time for recording by adding 

total_second -= {value}

under trim_audio_based_on clipboard in ffmpeg.py, but this is somewhat difficult to get to. Having this setting under config.toml makes it a lot easier for users to edit their preferred buffer time.

**Comment by bpwhelan** [comment]
Yep this was in my head at some point but i forgot. Will implement at some point

**Comment by bpwhelan** [comment]
Closed with #23
